---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt::default]
  - name: centos-6.5
  - name: debian-7.2.0
    run_list:
      - recipe[apt::default]
suites:
  - name: default
    run_list:
      - recipe[virtualbox::default]
      - recipe[virtualbox::webservice]
      - recipe[virtualbox::webportal]
    attributes: 
